create database purchasingmanagementsystem;
use purchasingmanagementsystem;

CREATE TABLE STATUS (
STATUS_ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(40) NOT NULL);

CREATE TABLE DEPARTMENT (
DEPARTMENT_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DEPARTMENT_NAME VARCHAR(100) NOT NULL,
IS_ACTIVE BIT(1) NOT NULL
);

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
IDENTIFICATION_NUMBER VARCHAR(11) NOT NULL,
FIRST_NAME VARCHAR(60) NOT NULL,
LAST_NAME VARCHAR(60) NOT NULL,
DEPARTMENT_ID INT NOT NULL,
ISACTIVE CHAR(1) NOT NULL,
CONSTRAINT FK_DEPARTMENT_EMPLOYEE FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
                        
CREATE TABLE BRAND (
BRAND_ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(200) NOT NULL,
IS_ACTIVE BIT(1) NOT NULL);

CREATE TABLE MEASUREMENT_UNIT (
UNIT_ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(200) NOT NULL,
IS_ACTIVE BIT(1) NOT NULL);

CREATE TABLE SUPPLIER (
SUPPLIER_ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(200) NOT NULL,
IDENTIFICATION_NUMBER VARCHAR(11) NOT NULL,
COMERCIAL_NAME VARCHAR(25) NOT NULL,
IS_ACTIVE BIT(1) NOT NULL);


CREATE TABLE ARTICLE (
ARTICLE_ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(50) NOT NULL,
BRAND_ID INT,
MEASUREMENT_UNIT_ID INT,
EXISTANCE INT NOT NULL,
IS_ACTIVE BIT(1) NOT NULL,
PRICE DECIMAL(8,2) NOT NULL,
CONSTRAINT FK_BRAND_ARTICLE FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID),
CONSTRAINT FK_MEASURMENT_ARTICLE FOREIGN KEY (MEASUREMENT_UNIT_ID) REFERENCES MEASUREMENT_UNIT(UNIT_ID)
);

CREATE TABLE ARTICLE_REQUEST (
REQUEST_ID INT PRIMARY KEY AUTO_INCREMENT,
EMPLOYEE_ID INT,
REQUEST_DATE DATE NOT NULL,
ARTICLE_ID INT,
QUANTITY INT NOT NULL,
MEASUREMENT_UNIT_ID INT NOT NULL,
IS_ACTIVE BIT(1) NOT NULL,
STATUS_ID INT,
CONSTRAINT FK_ARTICLE_REQUEST FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID),
CONSTRAINT FK_EMPLOYEE_REQUEST FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
CONSTRAINT FK_MEASURMENT_REQUEST FOREIGN KEY (MEASUREMENT_UNIT_ID) REFERENCES MEASUREMENT_UNIT(UNIT_ID),
CONSTRAINT FK_STATUS_REQUEST FOREIGN KEY (STATUS_ID) REFERENCES STATUS(STATUS_ID)
);

CREATE TABLE SHOPPING_ORDER (
ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
ORDER_DATE DATE NOT NULL,
STATUS_ID INT,
SUPPLIER_ID INT,
CONSTRAINT FK_SUPPLIER_ORDER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
CONSTRAINT FK_STATUS_SHOPPING FOREIGN KEY (STATUS_ID) REFERENCES STATUS(STATUS_ID)
);

CREATE TABLE SHOPPING_ORDER_DETAIL (
ORDER_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT,
SHOPPING_ORDER_ID INT,
PRICE DECIMAL(8 , 2 ) NOT NULL,
QUANTITY INT NOT NULL,
ARTICLE_ID INT,
ARTICLE_NAME INT,
REQUEST_ID INT,
MEASUREMENT_UNIT_ID INT,
CONSTRAINT FK_MEASURMENT_ORDER FOREIGN KEY (MEASUREMENT_UNIT_ID) REFERENCES MEASUREMENT_UNIT(UNIT_ID),
CONSTRAINT FK_ARTICLE_ORDER FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID),
CONSTRAINT FK_REQUEST_ORDER FOREIGN KEY (REQUEST_ID) REFERENCES ARTICLE_REQUEST(REQUEST_ID),
CONSTRAINT FK_SHOPPING_ORDER FOREIGN KEY (SHOPPING_ORDER_ID) REFERENCES SHOPPING_ORDER(ORDER_ID)
);
